import React, { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '../context/AuthContext';
import { apiService } from '../services/apiService';
import { getAgreementPickupDateTime } from '../utils/dateUtils';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, Cell
} from 'recharts';
import { format, subMonths, startOfMonth, endOfMonth, isWithinInterval } from 'date-fns';
import { Car, DollarSign, Calendar, TrendingUp } from 'lucide-react';

const VehicleRevenueReport: React.FC = () => {
  const { subscriberId } = useAuth();
  const [selectedMonth, setSelectedMonth] = useState<Date>(startOfMonth(new Date()));

  // Generate last 12 months for selector
  const monthOptions = useMemo(() => {
    const options = [];
    for (let i = 0; i < 12; i++) {
      options.push(startOfMonth(subMonths(new Date(), i)));
    }
    return options;
  }, []);

  const { data, isLoading } = useQuery({
    queryKey: ['admin-dashboard-data', subscriberId],
    queryFn: async () => {
      if (!subscriberId) throw new Error('No subscriber ID');
      const [agreements, cars] = await Promise.all([
        apiService.getAgreements(subscriberId),
        apiService.getCars(subscriberId)
      ]);
      return { agreements, cars };
    },
    enabled: !!subscriberId
  });

  const currencyFormatter = new Intl.NumberFormat('en-MY', {
    style: 'currency',
    currency: 'MYR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  });

  const { vehicleData, totalRevenue, totalBookings } = useMemo(() => {
    if (!data) return { vehicleData: [], totalRevenue: 0, totalBookings: 0 };

    const start = startOfMonth(selectedMonth);
    const end = endOfMonth(selectedMonth);

    const completedAgreements = data.agreements.filter(a => {
      const status = a.status?.toLowerCase().trim();
      const payoutStatus = a.payout_status?.toLowerCase().trim();
      
      // Only recognize sales if the agreement is completed AND it has been audited (approved or paid)
      if (status !== 'completed' || (payoutStatus !== 'approved' && payoutStatus !== 'paid')) {
        return false;
      }
      
      const pickupDateObj = getAgreementPickupDateTime(a);
      return isWithinInterval(pickupDateObj, { start, end });
    });

    const revenueByCar: Record<string, { total: number; count: number }> = {};
    let totalRev = 0;
    
    completedAgreements.forEach(a => {
      const plate = a.car_plate_number || 'Unknown';
      const price = a.total_price || 0;
      
      if (!revenueByCar[plate]) {
        revenueByCar[plate] = { total: 0, count: 0 };
      }
      revenueByCar[plate].total += price;
      revenueByCar[plate].count += 1;
      totalRev += price;
    });

    const formattedData = Object.entries(revenueByCar)
      .map(([plate, stats]) => {
        // Try to find the car model
        const carInfo = data.cars.find(c => c.plate === plate);
        const name = carInfo ? `${carInfo.make || ''} ${carInfo.model || carInfo.name}`.trim() : 'Unknown Model';
        
        return {
          plate,
          name,
          revenue: stats.total,
          bookings: stats.count
        };
      })
      .sort((a, b) => b.revenue - a.revenue);

    return { 
      vehicleData: formattedData, 
      totalRevenue: totalRev,
      totalBookings: completedAgreements.length
    };
  }, [data, selectedMonth]);

  if (isLoading) {
    return (
      <div className="flex-1 p-8 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-slate-900"></div>
      </div>
    );
  }

  // Generate colors for chart
  const colors = ['#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#d946ef', '#ec4899', '#f43f5e'];

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-8">
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-semibold text-slate-900 tracking-tight">Vehicle Revenue Report</h1>
            <p className="text-slate-500 mt-2 text-sm">
              Deep breakdown of rental sales generated by each vehicle. Data is strictly based on audited Digital Forms (Approved / Paid).
            </p>
          </div>
          
          <div className="flex items-center gap-3 bg-white border border-slate-200 p-2 rounded-xl shadow-sm">
            <Calendar className="w-5 h-5 text-slate-400 ml-2" />
            <select
              value={selectedMonth.toISOString()}
              onChange={(e) => setSelectedMonth(new Date(e.target.value))}
              className="border-0 bg-transparent text-slate-900 font-medium focus:ring-0 cursor-pointer py-1 pr-8"
            >
              {monthOptions.map((date, idx) => (
                <option key={idx} value={date.toISOString()}>
                  {format(date, 'MMMM yyyy')}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex items-center gap-4">
            <div className="bg-blue-50 p-4 rounded-full text-blue-600">
              <DollarSign className="w-8 h-8" />
            </div>
            <div>
              <p className="text-sm font-medium text-slate-500">Total Revenue ({format(selectedMonth, 'MMM')})</p>
              <h3 className="text-3xl font-bold text-slate-900">{currencyFormatter.format(totalRevenue)}</h3>
            </div>
          </div>
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex items-center gap-4">
            <div className="bg-emerald-50 p-4 rounded-full text-emerald-600">
              <TrendingUp className="w-8 h-8" />
            </div>
            <div>
              <p className="text-sm font-medium text-slate-500">Total Bookings</p>
              <h3 className="text-3xl font-bold text-slate-900">{totalBookings}</h3>
            </div>
          </div>
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex items-center gap-4">
            <div className="bg-purple-50 p-4 rounded-full text-purple-600">
              <Car className="w-8 h-8" />
            </div>
            <div>
              <p className="text-sm font-medium text-slate-500">Active Vehicles</p>
              <h3 className="text-3xl font-bold text-slate-900">{vehicleData.length}</h3>
            </div>
          </div>
        </div>

        {/* Chart */}
        {vehicleData.length > 0 ? (
          <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
            <h3 className="text-lg font-bold text-slate-900 mb-6">Revenue by Vehicle</h3>
            <div className="h-[400px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={vehicleData} margin={{ top: 20, right: 30, left: 20, bottom: 60 }}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                  <XAxis 
                    dataKey="plate" 
                    axisLine={false}
                    tickLine={false}
                    tick={{ fill: '#64748b', fontSize: 12 }}
                    angle={-45}
                    textAnchor="end"
                  />
                  <YAxis 
                    axisLine={false}
                    tickLine={false}
                    tick={{ fill: '#64748b', fontSize: 12 }}
                    tickFormatter={(value) => `RM${value}`}
                  />
                  <RechartsTooltip 
                    cursor={{ fill: '#f1f5f9' }}
                    contentStyle={{ borderRadius: '12px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                    formatter={(value: any) => [currencyFormatter.format(value as number), 'Revenue']}
                    labelStyle={{ color: '#0f172a', fontWeight: 'bold', marginBottom: '4px' }}
                  />
                  <Bar dataKey="revenue" radius={[6, 6, 0, 0]} maxBarSize={60}>
                    {vehicleData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={colors[index % colors.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        ) : (
          <div className="bg-white p-12 rounded-xl border border-slate-200 shadow-sm text-center">
            <div className="mx-auto w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mb-4">
              <Car className="w-8 h-8 text-slate-300" />
            </div>
            <h3 className="text-lg font-medium text-slate-900">No Revenue Data</h3>
            <p className="text-slate-500 mt-1">There are no audited (approved) agreements for {format(selectedMonth, 'MMMM yyyy')}.</p>
          </div>
        )}

        {/* Details Table */}
        {vehicleData.length > 0 && (
          <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-6 border-b border-slate-200">
              <h3 className="text-lg font-bold text-slate-900">Vehicle Breakdown</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-200">
                <thead className="bg-slate-50">
                  <tr>
                    <th scope="col" className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                      Vehicle Plate
                    </th>
                    <th scope="col" className="px-6 py-4 text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                      Model / Description
                    </th>
                    <th scope="col" className="px-6 py-4 text-center text-xs font-semibold text-slate-500 uppercase tracking-wider">
                      Total Bookings
                    </th>
                    <th scope="col" className="px-6 py-4 text-right text-xs font-semibold text-slate-500 uppercase tracking-wider">
                      Revenue Generated
                    </th>
                    <th scope="col" className="px-6 py-4 text-right text-xs font-semibold text-slate-500 uppercase tracking-wider">
                      % of Total
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-slate-200">
                  {vehicleData.map((row, idx) => (
                    <tr key={idx} className="hover:bg-slate-50 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center gap-3">
                          <div className="w-2 h-2 rounded-full" style={{ backgroundColor: colors[idx % colors.length] }}></div>
                          <span className="font-bold text-slate-900 bg-slate-100 px-2.5 py-1 rounded-md text-sm border border-slate-200">
                            {row.plate}
                          </span>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600 font-medium">
                        {row.name}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-600 text-center font-medium">
                        {row.bookings}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900 text-right font-bold">
                        {currencyFormatter.format(row.revenue)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-500 text-right">
                        {totalRevenue > 0 ? ((row.revenue / totalRevenue) * 100).toFixed(1) : 0}%
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default VehicleRevenueReport;
